services:
  runner:
    image: ${IMAGE}
    environment:
      CONTAINER_WORKSPACE:
      USER:
      USER_ID:
      JUPYTER_TOKEN:
      JUPYTER_PORT:
    ports:
      - "${JUPYTER_PORT}:${JUPYTER_PORT}"
    volumes:
      - "${HOST_PACKAGE_DIR}:${CONTAINER_PACKAGE_DIR}"
      - "${HOST_EXAMPLE_DIR}:${CONTAINER_EXAMPLE_DIR}"
      - "${PWD}/start.sh:/start.sh"
    command: "/start.sh"
