services:
  runner:
    image: ${IMAGE}
    environment:
      CONTAINER_WORKSPACE:
      USER:
      USER_ID:
    ports:
      - "8888:8888"
    volumes:
      - "${HOST_PACKAGE_DIR}:${CONTAINER_PACKAGE_DIR}"
      - "${HOST_EXAMPLE_DIR}:${CONTAINER_EXAMPLE_DIR}"
      - "${PWD}/start.sh:/start.sh"
    command: "/start.sh"
