version: '3'
services:
  gap-equideg-test:
    image: ${IMAGE}
    volumes:
      - "${HOST_PACKAGE_DIR}:${CONTAINER_PACKAGE_DIR}"
    command:
      [
        "gap",
        "-A",
        "-x",
        "80",
        "-m",
        "100m",
        "-o",
        "1g",
        "-K",
        "2g",
        "equideg/tst/testall.g"
      ]
