services:
  gap-equideg-dev:
    image: ${IMAGE}
    ports:
      - "8888:8888"
    volumes:
      - "${HOST_PACKAGE_DIR}:${CONTAINER_PACKAGE_DIR}"
      - "${HOST_TEST_DIR}:${CONTAINER_TEST_DIR}"
    command:
      [
        "jupyter",
        "notebook",
        "--allow-root",
        "--ip=0.0.0.0",
        "--no-browser"
      ]
