#############################################################################
##
#W  DirectProduct.gd	GAP Package `EquiDeg'			    Haopin Wu
##
#Y  Copyright (C) 2017-2018, Haopin Wu
#Y  Department of Mathematics, National Tsing Hua University, Taiwan
##
##  This file contains declarations for procedures related to direct proudct
##  of finite groups.
##
##  Todo:
##

#############################################################################
##

#############################################################################
##
#A  DirectProductDecomposition( <G> )
#A  DirectProductDecomposition( <c> )
#O  DirectProductDecomposition( <G>, <e> )
##
##  <#GAPDoc Label="DirectProductDecomposition">
##  <ManSection Label="DirectProductDecomposition">
##  <Heading>DirectProductDecomposition</Heading>
##  <Attr Name="DirectProductDecomposition" Label="group" Arg="G"/>
##  <Attr Name="DirectProductDecomposition" Label="conjugacy class" Arg="c"/>
##  <Oper Name="DirectProductDecomposition" Label="group element" Arg="G, e"/>
##  <Description>
##  <C>DirectProductDecomposition</C> performs
##  direct product decomposition for either
##  a <E>group</E>,
##  a <E>conjugacy class</E> or
##  a <E>group element</E>.
##  <Br/><Br/>
##
##  Here is an example.
##  <Example>
##  gap> G1 := SymmetricGroup( 4 );;
##  gap> G2 := CyclicGroup( 2 );;
##  gap> G := DirectProduct( G1, G2 );;
##
##  gap> DirectProductDecomposition( G ); # for group
##  [ Sym( [ 1 .. 4 ] ), Group([ (1,2) ]) ]
##  gap> c := ConjugayClasses( G )[ 10 ];
##  (1,2,3,4)(5,6)^G
##  gap> DirectProductDecomposition( c ); # for conjugacy class
##  [ (1,2,3,4)^G, (1,2)^G ]
##  gap> e := List( G )[ 30 ];
##  (1,3,2)(5,6)
##  gap> DirectProductDecomposition( G, e ); # for group element
##  [ (1,3,2), (1,2) ]
##  </Example>
##  </Description>
##  </ManSection>
##  <#/GAPDoc>
##
  DeclareAttribute( "DirectProductDecomposition", IsGroup );
  DeclareAttribute( "DirectProductDecomposition",
      IsConjugacyClassGroupRep );
  DeclareOperation( "DirectProductDecomposition",
      [ IsGroup, IsMultiplicativeElementWithInverse ] );

#############################################################################
##
#A  TensorProductDecomposition( <chi> )
##
##  <#GAPDoc Label="TensorProductDecomposition">
##  <ManSection>
##  <Attr Name="TensorProductDecomposition" Arg="chi"/>
##  <Description>
##  This is an attribute of an irreducible character
##  of a group generated by direct product which
##  contains its tensor product decomposition.
##  <Br/><Br/>
##
##  Here is an example (which continues the example in
##  <Ref Subsect="DirectProductDecomposition"/>):
##  <Example>
##  gap> chi := Irr( G )[ 7 ];
##  Character( CharacterTable( Group([ (1,2,3,4), (1,2), (5,6) ]) ),
##   [ 3, -3, -1, 1, 0, 0, -1, 1, 1, -1 ] )
##  gap> TensorProductDecomposition( chi );
##  [ Character( CharacterTable( Sym( [ 1 .. 4 ] ) ), [ 3, -1, -1, 0, 1 ] ),
##    Character( CharacterTable( Sym( [ 1 .. 2 ] ) ), [ 1, -1 ] ) ]
##  </Example>
##  </Description>
##  </ManSection>
##  <#/GAPDoc>
##
  DeclareAttribute( "TensorProductDecomposition", IsCharacter );

#############################################################################
##
#A  GoursatInfo( <U> )
#A  GoursatInfo( <C> )
##
##  <#GAPDoc Label="GoursatInfo">
##  <ManSection>
##  <Heading>GoursatInfo</Heading>
##  <Attr Name="GoursatInfo" Label="for subgroup" Arg="U"/>
##  <Attr Name="GoursatInfo" Label="for CCS" Arg="C"/>
##  <Description>
##  This attribute contains the information
##  that describes subgroup <A>U</A> or
##  conjugacy class of subgroups <A>C</A> of
##  the direct product of two groups
##  (related to Goursat lemma).
##  </Description>
##  </ManSection>
##  <#/GAPDoc>
##
  DeclareAttribute( "GoursatInfo", IsGroup and HasParentAttr );
  DeclareAttribute( "GoursatInfo", IsConjugacyClassSubgroupsRep );

#############################################################################
##
#F  AmalgamationSymbol( <C> )
##
##  <#GAPDoc Label="AmalgamationSymbol">
##  <ManSection>
##  <Oper Name="AmalgamationSymbol" Arg="C"/>
##  <Description>
##    This operation returns amalgamation symbol
##    of CCS <A>C</A> of the direct product of two groups.
##  </Description>
##  </ManSection>
##  <#/GAPDoc>
##
  DeclareOperation( "AmalgamationSymbol",
      [ IsConjugacyClassSubgroupsRep ] );


#############################################################################
##
#E  DirectProduct.gd . . . . . . . . . . . . . . . . . . . . . . .  ends here
