name: ci on push

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test GAP package
        run: |
          cd tst
          docker-compose up --exit-code-from tester
