name: Regular test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: run test in docker env
        run: |
          docker-compose -f deployment/docker-compose-test.yml up --exit-code-from package-test
